server: 
  port: 8888

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myTest?useUnicode=true&characterEncoding=utf8
    username: root
    password: aa223183.

mybatis:
  type-aliases-package: org.alanhou.model
  mapper-locations: classpath*:mapper/*Mapper.xml
#    - mapper/*